---
title: "Final Project"
author: "Aziz    aaa169@pitt.edu"
date: "October 14, 2016"
output: html_document
---



```{r}

setwd("./Documents/Master/Data Mining/Project/Pittsburgh-Bike-Share-Project/")

```

```{r}
### Get the data

setwd("./data/")

```


```{r}
library(lubridate)
library(dplyr)
library(ggplot2)


```

```{r}
## Read The data
### stations data
stations <- read.csv("HealthyRideStations2015.csv")

```

```{r}

## 2015 Q3

rentalQ153 <- read.csv("HealthyRideRentals 2015 Q3.csv",na.strings= c("999", "NA", " ", ""))  


### Change the data 

rentalQ153$StartTime <- strptime(rentalQ153$StartTime, format="%m/%d/%Y %H:%M")
rentalQ153$StopTime <- strptime(rentalQ153$StopTime, format="%m/%d/%Y %H:%M")

# rentalQ153$StartTime <- as.POSIXct(rentalQ153$StartTime, format="%m/%d/%Y %H:%M")
# rentalQ153$StopTime <- as.POSIXct(rentalQ153$StopTime, format="%m/%d/%Y %H:%M")



```

```{r}

## 2015 Q4

## Converting from xls to csv

# require(gdata)
# ## install support for xlsx files
# installXLSXsupport()
# excelFile <- ("./HealthyRideRentals 2015 Q4.xlsx")
# ## note that the perl scripts that gdata uses do not cope well will tilde expansion
# ## on *nix machines. So use the full path. 
# numSheets <- sheetCount(excelFile, verbose=TRUE)
# 
# for ( i in 1:numSheets) {
#   mySheet <- read.xls(excelFile, sheet=i)
#   write.csv(mySheet, file=paste(i, "csv", sep="."), row.names=FALSE)
# }

rentalQ154 <- read.csv("HealthyRideRentals 2015 Q4.csv", na.strings= c("999", "NA", " ", ""))  
rentalQ154$StartTime <- strptime(rentalQ154$StartTime, format="%Y-%m-%d %H:%M:%S")
rentalQ154$StopTime <- strptime(rentalQ154$StopTime, format="%Y-%m-%d %H:%M:%S")

# rentalQ154$StartTime <- as.POSIXct(rentalQ154$StartTime)
# rentalQ154$StopTime <- as.POSIXct(rentalQ154$StopTime)


```


```{r}

## 2016 Q1

## Converting from xls to csv

# require(gdata)
# ## install support for xlsx files
# installXLSXsupport()
# excelFile <- ("./HealthyRide Rentals 2016 Q1.xlsx")
# ## note that the perl scripts that gdata uses do not cope well will tilde expansion
# ## on *nix machines. So use the full path.
# 
# 
# mySheet <- read.xls(excelFile)
# write.csv(mySheet, file=paste("HealthyRide Rentals 2016 Q1","csv", sep="."), row.names=FALSE)

rentalQ161 <- read.csv("HealthyRide Rentals 2016 Q1.csv", na.strings= c("999", "NA", " ", ""))  
## Make sure they have the same colunm names 
names(rentalQ161) <- c(names(rentalQ153))

rentalQ161$StartTime <- strptime(rentalQ161$StartTime, format="%Y-%m-%d %H:%M:%S")
rentalQ161$StopTime <- strptime(rentalQ161$StopTime, format="%Y-%m-%d %H:%M:%S")

# rentalQ161$Starttime <- as.POSIXct(rentalQ161$Starttime,format="%Y-%m-%d %H:%M:%S")
# rentalQ161$Stoptime <- as.POSIXct(rentalQ161$Stoptime,format="%Y-%m-%d %H:%M:%S")






```

```{r}

## binding the data together

bike <- rbind(rentalQ153,rentalQ154,rentalQ161)

bike$TripId <- as.factor(bike$TripId)
bike$BikeId <- as.factor(bike$BikeId)
bike$FromStationId <- as.factor(bike$FromStationId)
bike$ToStationId <- as.factor(bike$ToStationId)

```


```{r}

## Splitting the date 



# bike <- bike %>% mutate(
#   year = format(as.POSIXct(StartTime), format = "%Y"),
#   month = format(as.POSIXct(StartTime), format = "%m"),
#   day = format(as.POSIXct(StartTime), format = "%d"),
#   hour = format(as.POSIXct(StartTime), format= "%H")
# )


set_up_features <- function(df) {
  ### Start Time 
  df$StartTime <- strptime(df$StartTime, format="%Y-%m-%d %H:%M:%S")
  df$StartHour <- as.factor(df$StartTime$hour)
  df$StartDay <-  as.factor(df$StartTime$mday)
  df$StartWday <- as.factor(df$StartTime$wday)
  df$StartMonth <- as.factor(df$StartTime$mon+1) ## starts from 0
  df$StartYear <- as.factor(df$StartTime$year + 1900)
  
  ### Stop Time
  df$StopTime <- strptime(df$StopTime, format="%Y-%m-%d %H:%M:%S")
  df$StopHour <- as.factor(df$StopTime$hour)
  df$StopDay <-  as.factor(df$StopTime$mday)
  df$StopWday <- as.factor(df$StopTime$wday)
  df$StopMonth <- as.factor(df$StopTime$mon+1) ## starts from 0
  df$StopYear <- as.factor(df$StopTime$year + 1900)
  
  df
}

bike <- set_up_features(bike)
  
```

```{r}

## Make a summeary for the missing values 

na_data <- sapply(bike, function(x) sum(length(which(is.na(x)))))
na_data


```

```{r}

bike$FromStationName[which(is.na(bike$FromStationId))]

bike$FromStationId[which(is.na(bike$FromStationName))]

## I guss we should just drop them

```

```{R}

detach("package:plyr", unload=TRUE) 

```

```{r}
### Remove all NA values 

bike <- na.omit(bike)


```

```{r}
## Remove the station "Transit" and "Healthy Ride Hub"

## 687
 bike %>% 
  select(TripId, FromStationId) %>% 
    filter(FromStationId %in% c(1050,1051)) %>% 
      summarise(n())

## 790
bike %>%
    select(TripId, ToStationId) %>%
    filter(ToStationId %in% c(1050,1051)) %>%
    summarise(n())


```

```{r}

### Drop these values 
 bike <- bike[!bike$FromStationId %in% c(1050,1051) & !bike$ToStationId %in% c(1050,1051),]

```


```{r}

# # weather$DATE <- as.factor(weather$DATE$year + 1900)
# set_up_featuresDate <- function(df) {
#   df$day <-  as.factor(df$date$mday)
#   df$month <- as.factor(df$date$mon+1) ## starts from 0
#   df$year <- as.factor(df$date$year + 1900)
#   df
# }
# 
# weather <- set_up_featuresDate(weather)


```

```{r}

# weather <- weather[,-1]

```


```{r}


# bike1 <- merge(weather, bike, by = c("day","month","year"))
# bike1 <- join(bike, weather_holidays,  by=c("Day",'Month','Year'), type="inner")
# semi_join(bike, weather)

```


```{r}
## Write a csv file "bike.csv"

write.csv(bike, file = "./bike.csv", row.names = FALSE)


```

```{r}

##################### This Section is to make exploratory graph #######################

## Trying to make some useful graphs 

newBike <- bike

## Delete the row that has month 6
newBike <- newBike[!newBike$StartMonth==6,]

newBike$StartHour <- as.numeric(levels(newBike$StartHour))[newBike$StartHour]
newBike$StartDay <- as.numeric(levels(newBike$StartDay))[newBike$StartDay]
#newBike$StartMonth <- as.numeric(levels(newBike$StartMonth))[newBike$StartMonth]
#newBike$StartYear <- as.numeric(levels(newBike$StartYear))[newBike$StartYear]

newBike$StopHour <- as.numeric(levels(newBike$StopHour))[newBike$StopHour]
newBike$StopDay <- as.numeric(levels(newBike$StopDay))[newBike$StopDay]
#newBike$StopMonth <- as.numeric(levels(newBike$StopMonth))[newBike$StopMonth]
#newBike$StopYear <- as.numeric(levels(newBike$StopYear))[newBike$StopYear]


```

```{r}

### The Dirstibution of bike rented per hours 
ggplot(newBike, aes(StartHour, fill=StartYear))  + ggtitle("Rented Bikes Per Hour") +
  labs(x="Hour")  + geom_density(alpha=0.5) +  theme_bw()

### The Dirstibution of bike rented per Day 
ggplot(newBike, aes(StartDay, fill=StartMonth))  + ggtitle("Rented Bikes Per Day") +
  labs(x="Day")  + geom_histogram(binwidth = 0.5) +  theme_bw() + facet_grid(StartMonth~StartYear)

## For the month
ggplot(newBike, aes(StartMonth, fill = StartYear)) + geom_bar()

##### for Stop time ############


### The Dirstibution of bike rented per hours 
ggplot(newBike, aes(StopHour, fill=StopYear))  + ggtitle("Rented Bikes Returned per hour") +
  labs(x="Hour")  + geom_density(alpha=0.5) +  theme_bw()

### The Dirstibution of bike rented per Day 
ggplot(newBike, aes(StopDay, fill=StopMonth))  + ggtitle("Rented Bikes Returned Per Day") +
  labs(x="Day")  + geom_histogram(binwidth = 0.5) +  theme_bw() + facet_grid(StopMonth~StopYear)

## For the month
ggplot(newBike, aes(StopMonth, fill = StopYear)) + geom_bar()


```



```{r}

## Calcuate the counts
# by Hour, Day, Month, Year
# inclue the From station Id
starttime <- bike[,c(6,11,12,14,15)]
stoptime <- bike[,c(8,16,17,19,20)]


```

```{r}
## Calcuate the counts

# starttime <- count_(starttime, c('StartHour','StartDay','StartMonth','StartYear'))
# stoptime <- count_(stoptime,  c('StopHour','StopDay','StopMonth','StopYear'))

starttime <- starttime %>% count(FromStationId, StartHour,StartDay, StartMonth, StartYear)
stoptime <- stoptime %>% count(ToStationId, StopHour, StopDay, StopMonth, StopYear)
```

```{r}

## Aggregation for Hour and FromStationId and ToStationid


# aggregate_starttime_hour <- starttime %>% 
#   group_by(FromStationId,StartHour,StartDay,StartMonth,StartYear) %>% 
#   summarise_each(funs(sum), n) %>% 
#   arrange(StartYear, StartMonth)

aggregate_starttime_hour <- starttime %>% 
  group_by(StartHour,StartDay,StartMonth,StartYear) %>% 
  summarise_each(funs(sum), n) %>% 
  arrange(StartYear, StartMonth)

# aggregate_stoptime_hour <- stoptime %>%
#   group_by(ToStationId,StopHour, StopDay, StopMonth, StopYear) %>%
#   summarise_each(funs(sum), n) %>%
#   arrange(StopYear, StopMonth)

```

```{r}
## Aggregation per day and FromStationId and ToStationid
## used for classification

aggregate_starttime_day <- starttime %>% 
  group_by(FromStationId,StartDay,StartMonth,StartYear) %>% 
  summarise_each(funs(sum), n) %>% 
  arrange(StartYear, StartMonth)



aggregate_stoptime_day <- stoptime %>%
  group_by(ToStationId,StopDay, StopMonth, StopYear) %>%
  summarise_each(funs(sum), n) %>%
  arrange(StopYear, StopMonth)


```


```{r}

library(plyr)

### Weather 

### Holiday column 1 means it is either a holiday or a weekend 
### Weekend 1 = yes , 0 = no
## Types 1 = Sunny, 2 = Rain, 3 = Snow

# weather <- read.csv("weather.csv")
weather_holidays <- read.csv("weather_holiday.csv", stringsAsFactors = TRUE)
weather_holidays$Day <- as.factor(weather_holidays$Day)
weather_holidays$Month <- as.factor(weather_holidays$Month)
weather_holidays$Year <- as.factor(weather_holidays$Year)
weather_holidays$Holiday <- as.factor(weather_holidays$Holiday)
weather_holidays$Weekend <- mapvalues(weather_holidays$Weekend, from = c('yes','no'), to = c(1,0))
weather_holidays$Types <- mapvalues(weather_holidays$Types, from = c('Sunny','Rain','Snow'), to = c(1,2,3))

```

```{r}

### Merge the aggregate_starttime_hour with the holdiay and the weather 
### This is just used for the prediction 

bike_final <-merge(aggregate_starttime_hour, weather_holidays, by.x = c('StartDay','StartMonth','StartYear'), by.y = c('Day','Month','Year'))
bike_final <- arrange(bike_final,StartYear,StartMonth, StartDay, StartHour)


```

```{r}

## For classification we need two separete files to find out the unbalance problem
## bike_starttime and bike_stoptime

bike_starttime <- merge(aggregate_starttime_day, weather_holidays, by.x = c('StartDay','StartMonth','StartYear'), by.y = c('Day','Month','Year'))
bike_starttime <- arrange(bike_starttime, StartYear, StartMonth, StartDay)


bike_stoptime <- merge(aggregate_stoptime_day, weather_holidays, by.x = c('StopDay','StopMonth','StopYear'), by.y = c('Day','Month','Year'))
bike_stoptime <- arrange(bike_stoptime, StopYear, StopMonth, StopDay)

```

```{r}

### Make useful graph for the starttime 

### We need to see the correlation between the weather and the number of rented bikes 
## As the temprature increase the number of bikes rented increase 
ggplot(bike_starttime, aes(x=Mean.Temp, y=n)) + geom_point(shape=1) + geom_smooth(method="lm",position = "identity" ,se = FALSE) + theme_bw() + ggtitle("Temperature effect on number of rented bikes")

### Check it with the holiday
ggplot(bike_starttime, aes(x=Mean.Temp, y=n, color = Holiday)) + geom_point(shape=1) +  theme_bw() + ggtitle("Temperature effect on number of rented bikes on holidays")


### No effect with humidity
ggplot(bike_starttime, aes(x=Mena.Humidity, y=n)) + geom_point(shape=1) + geom_smooth(method="lm",position = "identity" ,se = FALSE) + theme_bw() + ggtitle("Temperature effect on number of rented bikes")

### There is a slighlty negative correlation with wind
ggplot(bike_starttime, aes(x=Mean.Wind , y=n)) + geom_point(shape=1) + geom_smooth(method="lm",position = "identity" ,se = FALSE) + theme_bw() + ggtitle("Temperature effect on number of rented bikes")

```


```{r}

####### Not Right - Must be fixed #####
#######################
bikeTest<-merge(bike_starttime, stations, by.x = "FromStationId", by.y = "StationNum")
bike_starttime$diff <- bike_starttime$n- bike_stoptime$n
bikeTest$rentedBikes<- bikeTest$diff/bikeTest$RackQnty
bikeTest$rentedBikes[bikeTest$rentedBikes!=0]=1
View(bikeTest)


```


```{r}
### Change the factors to numerics for prediction 

bike_final$StartHour <- as.numeric(levels(bike_final$StartHour))[bike_final$StartHour]
bike_final$StartDay <- as.numeric(levels(bike_final$StartDay))[bike_final$StartDay]
bike_final$StartMonth <- as.numeric(levels(bike_final$StartMonth))[bike_final$StartMonth]
bike_final$StartYear <- as.numeric(levels(bike_final$StartYear))[bike_final$StartYear]

str(bike_final)
```

```{r}


######################### Linear Regression ##############################
#########################################################################

### Splitting on train and test datasets 

biketrain<-subset(bike_final,bike_final$StartDay %in% c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19))


train<-as.data.frame(biketrain)
View(train)


biketest<-subset(bike_final,bike_final$StartDay %in% c(20,21,22,23,24,25,26,27,28,29,30,31))
test <- as.data.frame(biketest)
View(test)

str(train)
str(test)

```


```{R}


##### Linear regression #####

### Split the data to training and testing 

ytrain = train$n
ytest = test$n

m1 = lm(n~., data=train)
summary(m1)

ptest = predict(m1,newdata=test)
prediction_result <-  data.frame(ytest,ptest)
prediction_result$error = ptest - ytest

obs = ytest
error = ptest - obs

rmse=sqrt(mean(error^2))
rmse

## RMSE
rmse3 <- function(y, f) { sqrt(mean( (y-f)^2 )) } 
rmse3(ytest,ptest)


#### Plotting 

ggplot(data=prediction_result,aes(x=ptest,y=ytest)) + geom_point(alpha=0.2,color="black") + 
  geom_smooth(aes(x=ptest,
       y=ytest),color="black") +
  geom_line(aes(x=ytest,
                y=ytest,color="blue")) 


### ploting the residual 
ggplot(data=prediction_result,aes(x=ptest,
                      y=error)) +
  geom_point(alpha=0.2,color="black") +
  geom_smooth(aes(x=ptest,
                  y=error,
              color="black"))





```

```{r}

write.csv(bike_final, file = "./bike_final.csv", row.names = FALSE)
write.csv(bike_starttime, file = "./bike_starttime.csv", row.names = FALSE)
write.csv(bike_stoptime, file = "./bike_stoptime.csv", row.names = FALSE)


```



```{r}
####################### Warning ####################################
##### The next section is just for data exploration  #################

```


```{r}
## Get the weather and holidays
holiday <- weather_holidays[, c('Day','Month','Year','Weekend','Holiday')]
```

```{r}
## Merging them by 
starttime_holiday <- merge(starttime, holiday, by.x = c('StartDay','StartMonth','StartYear'), by.y = c('Day','Month','Year'))

stoptime_holiday <- merge(stoptime, holiday, by.x = c('StopDay','StopMonth','StopYear'), by.y = c('Day','Month','Year'))

```

```{r}
### Grouping by day to make useful viusalization 

aggregate_starttime_day_weatherHoliday <- merge(aggregate_starttime_day, weather_holidays, by.x = c('StartDay','StartMonth','StartYear'), by.y = c('Day','Month','Year'))

aggregate_starttime_day_weatherHoliday <- aggregate_starttime_day_weatherHoliday %>% arrange(StartYear,StartMonth,StartDay)

aggregate_starttime_day_weatherHoliday$Types <- as.integer(aggregate_starttime_day_weatherHoliday$Types)
aggregate_starttime_day_weatherHoliday$Weekend <- as.integer(aggregate_starttime_day_weatherHoliday$Weekend)
aggregate_starttime_day_weatherHoliday$Holiday <- as.integer(aggregate_starttime_day_weatherHoliday$Holiday)

View(aggregate_starttime_day_weatherHoliday)

```


```{r}


### Split them based on the holiday holiday
starttime_holiday_split <- split(starttime_holiday, starttime_holiday$Holiday)

starttime_holiday_no <- starttime_holiday_split[[1]]
starttime_holiday_yes <- starttime_holiday_split[[2]]

stoptime_holiday_split <- split(stoptime_holiday, stoptime_holiday$Holiday)

stoptime_holiday_no <- stoptime_holiday_split[[1]]
stoptime_holiday_yes <- stoptime_holiday_split[[2]]

```

```{r}
### aggregating with hour
starttime_holiday_yes_hour <- aggregate(n ~ StartHour , data = starttime_holiday_yes, sum)
starttime_holiday_no_hour <- aggregate(n ~ StartHour, data = starttime_holiday_no, sum)

stoptime_holiday_yes_hour <- aggregate(n ~ StopHour, data = stoptime_holiday_yes, sum)
stoptime_holiday_no_hour <- aggregate(n ~ StopHour, data = stoptime_holiday_no, sum)

```

```{r}

## Merging 

startstoptime_DMY <- merge(aggregate_starttime_day,aggregate_stoptime_day, by.x = c("StartDay","StartMonth","StartYear"), by.y = c("StopDay","StopMonth","StopYear"))

startstop_holiday_yes_hour <- merge(starttime_holiday_yes_hour, stoptime_holiday_yes_hour, by.x = "StartHour", by.y = "StopHour")

startstop_holiday_no_hour <- merge(starttime_holiday_no_hour, stoptime_holiday_no_hour, by.x = "StartHour", by.y = "StopHour")
```

```{r}


## Renaming 
startstoptime_DMY <- rename(startstoptime_DMY, c("n.x"="Out", "n.y"="In"))
startstop_holiday_yes_hour <- rename(startstop_holiday_yes_hour,  c("n.x"="Out", "n.y"="In"))
startstop_holiday_no_hour <- rename(startstop_holiday_no_hour,  c("n.x"="Out", "n.y"="In"))

```

```{r}
## Graphs


ggplot(aggregate_starttime_day, aes(x=n , fill = as.factor(StartYear))) + geom_density()
ggplot(aggregate_starttime_day, aes(x=log(n) , fill = as.factor(StartMonth))) + geom_density()
ggplot(aggregate_starttime_day, aes(x=n , fill = as.factor(StartDay))) + geom_density()

## based on weather types
ggplot(aggregate_starttime_day_weatherHoliday, aes(x=n, fill = as.factor(Types))) + geom_density()
ggplot(aggregate_starttime_day_weatherHoliday, aes(x=n, fill = as.factor(Holiday))) + geom_density()

### Histogram

par(mfrow=c(4,2))
par(mar = rep(2, 4))
hist(aggregate_starttime_day_weatherHoliday$Types)
hist(aggregate_starttime_day_weatherHoliday$Weekend)
hist(aggregate_starttime_day_weatherHoliday$Holiday)
hist(aggregate_starttime_day_weatherHoliday$Mean.Temp)
hist(aggregate_starttime_day_weatherHoliday$Mean.Wind)
hist(aggregate_starttime_day_weatherHoliday$Mean.Visib)
hist(aggregate_starttime_day_weatherHoliday$Mean.Visib)


# ggplot(starttime_holiday, aes(x=StartHour, y=n, color = Holiday)) + geom_point()
# 
# ggplot(starttime_holiday, aes(x=StartMonth, y=n)) + geom_point()
# 
# ggplot(starttime_holiday, aes(x=StartMonth)) + geom_line(aes(y= n, color = 'red'))



```



```{r}

### References
# https://github.com/artem-fedosov/bike-sharing-demand/blob/master/read_data.R
# https://www.analyticsvidhya.com/blog/2015/06/solution-kaggle-competition-bike-sharing-demand/

```